    # this one is important
SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

#set(CMAKE_SYSROOT path/to/raspbian/chroot)

set(CROSS_COMPILER_PREFIX "armv6-raspbian-linux-gnueabihf-")

# specify the cross compiler
SET(CMAKE_C_COMPILER ${CROSS_COMPILER_ROOT}${CROSS_COMPILER_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER ${CROSS_COMPILER_ROOT}${CROSS_COMPILER_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
